### ISSUE TITLE
Allow passing a nonce or hash for sites with strict CSPs

### ISSUE THREAD

**Issue by ztoben** [unrealmanu/ga-4-react#4]
Currently trying to use this library on our site, but can't because the tag manager script gets blocked by our csp. Allowing a nonce or hash to be passed would allow us to get past this I think.

**Comment by unrealmanu** [comment]
in the latest release i added your request, let me know if it works.
https://github.com/unrealmanu/ga-4-react/blob/main/README.md

**Comment by unrealmanu** [comment]
only for reference (from readme.md):
`const ga4react = new GA4React(
'YOUR GA CODE',
{ /* ga custom config, optional */ },
[ /* additional code, optional */ ],
5000 /* timeout, optional, defaults is 5000 */,
options /* { nonce: ['first-script-is-async','second-script'] } */

});
ga4react.initialize().then((ga4) => {
  ga4.pageview('path')
  ga4.gtag('event','pageview','path') // or your custom gtag event
},(err) => {
  console.error(err)
})`

**Comment by ztoben** [comment]
Maybe I'm initializing it wrong, but I don't see a nonce being set. This is in the error body I get back when I try to initialize:

![image](https://user-images.githubusercontent.com/4007345/105071958-de625c80-5a4a-11eb-876d-0f1172f905de.png)

Here's basically what I have for my init:

const ga4react = new GA4React(
  'gaMeaasurementKey',
  {},
  [],
  5000,
  {nonce: ['nonce1', 'nonce2']}
);

Am I doing something wrong?

**Comment by unrealmanu** [comment]
would you try to upgrade to version> = 0.1.271 please?

**Comment by ztoben** [comment]
Okay, seems like things are working fine in Chrome but it runs into an issue still in Firefox Developer Edition.

**Comment by unrealmanu** [comment]
I tried with firefox developer preview, it seems to me to go.
try clearing the cache or giving me more info

`(function () {
  const ga = new GA4React("xxx", {}, [], 5000, { nonce: ["nonce1", "nonce2"] });
  console.log(ga);
  ga.initialize().then((ga) => {
    console.log(ga);
  });
})();
`

<img width="874" alt="Schermata 2021-01-19 alle 20 51 40" src="https://user-images.githubusercontent.com/3137910/105085532-29ef2780-5a98-11eb-8852-374cca813c27.png">

**Comment by ztoben** [comment]
Ended up being an ad blocker, so everything is working as expected! Thanks!

**Comment by unrealmanu** [comment]
nothing! bye bye

**Comment by gidich** [comment]
To aid anyone else coming across this thread, I ended up using the hash approach instead of the nonce as I'm serving static content from a CDN. 

This is how I went about it:

To generate the CSP I hit pause in the google debugger to see specifically what code was being generated  (specifically ga4manager.tsx ~line 135), so depending on your options it may be different, I got something like this:
```
window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);};
        gtag('js', new Date());
        gtag('config', 'G-XXXXXXXXXX', {"debug_mode":false});
```
Then I used an [online hash generator](https://report-uri.com/home/hash) to get the create hash value. (in the example above, the hash would be: `sha256-IBkv3CC/Fwz7jbHfcCIlP19U0yv+7XjdPbTS4DBRBeg=`)

Read more on CSP with these resources

- [GA And CSP](https://developers.google.com/web/fundamentals/security/csp)
- [CSP Details](https://www.troyhunt.com/locking-down-your-website-scripts-with-csp-hashes-nonces-and-report-uri/)

Then used the following for my CSP header on our CDN rules.
```
    "content-security-policy": "default-src https: 'unsafe-eval' 'unsafe-inline' https://www.googletagmanager.com; object-src 'none'; script-src 'self' https://cdn.jsdelivr.net https://www.googletagmanager.com 'sha256-IBkv3CC/Fwz7jbHfcCIlP19U0yv+7XjdPbTS4DBRBeg='; img-src 'self' www.googletagmanager.com data:;"

```
More details on a full implementation of this library is documented on our GitBook site (hope it helps someone)

https://ecfmg.gitbook.io/azure-serverless-quickstart/adding-functionality/google-analytics
